---
ID: "27b43408-9ad2-4ed6-84b7-d416ee334504"
Parent: "954c8690-099b-4d4b-b588-63209cb0c1e2"
Template: "954c8690-099b-4d4b-b588-63209cb0c1e2"
Path: /sitecore/templates/Project/Capgemini/Data Templates/Carousel Slide/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221020T103546Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
